using System;

namespace backend.Models
{
    public class StaffSalary
    {
        public long SalaryId { get; set; }
        public long SalaryMasterId { get; set; } // Reference to the Master Record
        public int SalaryYearId { get; set; }
        public byte Month { get; set; }
        public int EmployeeId { get; set; }
        
        // Snapshot Columns
        public decimal BaseBasicPay { get; set; }
        public decimal PresentDays { get; set; }
        public int TotalDaysInMonth { get; set; }
        public string? AllowancesDetail { get; set; } // JSON string from DB
        public string? DeductionsDetail { get; set; } // JSON string from DB
        public bool IsFinalized { get; set; }

        public decimal NetSalary { get; set; } // This is Earned Basic Pay
        public decimal TotalAllowance { get; set; }
        public decimal TotalBaseAllowance { get; set; } // Mapping for preview, or calculated from JSON for saved records
        public decimal TotalDeduction { get; set; }
        
        // Computed Columns (can be calculated or mapped from DB)
        public decimal TotalSalWithoutDeduction => NetSalary + TotalAllowance;
        public decimal GrossSalary => NetSalary + TotalAllowance - TotalDeduction;
        
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        
        public string? EmployeeName { get; set; }
        public string? EmployeeCode { get; set; }
        public string? ProfilePictureUrl { get; set; }
    }

    public class CreateStaffSalaryRequest
    {
        public int OrganizationId { get; set; } // Needed to find/create the Master record
        public int SalaryYearId { get; set; }
        public int EmployeeId { get; set; }
        public byte Month { get; set; }
        public decimal BaseBasicPay { get; set; }
        public decimal PresentDays { get; set; }
        public int TotalDaysInMonth { get; set; }
        public string? AllowancesDetail { get; set; }
        public string? DeductionsDetail { get; set; }
        public decimal NetSalary { get; set; }
        public decimal TotalAllowance { get; set; }
        public decimal TotalDeduction { get; set; }
        public int CreatedBy { get; set; }
    }

    public class FinalizeSalaryRequest
    {
        public int SalaryYearId { get; set; }
        public byte Month { get; set; }
        public int EmployeeId { get; set; } // 0 for everyone
        public bool IsFinalized { get; set; }
    }

    public class PayrollPreviewModel
    {
        public int EmployeeId { get; set; }
        public string? EmployeeName { get; set; }
        public string? EmployeeCode { get; set; }
        public string? ProfilePictureUrl { get; set; }
        public decimal BaseBasicPay { get; set; }
        public decimal PresentDays { get; set; }
        public decimal TotalAllowance { get; set; }
        public decimal TotalBaseAllowance { get; set; }
        public decimal TotalDeduction { get; set; }
        public int TotalDaysInMonth { get; set; }
        
        // JSON details from DB (generated by FOR JSON PATH)
        public string? AllowancesDetail { get; set; }
        public string? DeductionsDetail { get; set; }

        public bool IsFinalized { get; set; } // If a record already exists
        
        // Logical Helpers
        public decimal EarnedBasicPay => TotalDaysInMonth > 0 ? (BaseBasicPay / TotalDaysInMonth) * PresentDays : 0;
        public decimal TotalSalWithoutDeduction => EarnedBasicPay + TotalAllowance;
        public decimal GrossSalary => TotalSalWithoutDeduction - TotalDeduction;
    }
}
